### PR TITLE
Sort available versions on 'missing version' page

### LINKED ISSUE #201: Sort versions on 'missing version' page
eg: https://pursuit.purescript.org/packages/purescript-prelude/9.9.9/docs/Prelude

The relevant code is in `Handler.Packages`.

### PR DESCRIPTION
**Pull request by stefanholzmueller**
should fix #201

### CODE REVIEW

**Comment by hdgarrood** [comment]
:+1: thank you!

**Comment by hdgarrood** [comment]
Oops, this is on your repo. I guess you probably wanted to open it on the real one, https://github.com/purescript/pursuit?

**Comment by hdgarrood** [comment]
I merged this manually: https://github.com/purescript/pursuit/commit/0c308d868f454e743035720eddfcc11db162fbc2 thank you!

**Comment by stefanholzmueller** [comment]
Well, it was late when I made the PR... thanks for picking the commit manually.

**Pull request closed without merging**
